### ISSUE TITLE
Stuck in "scanning offset"

### ISSUE THREAD

**Issue by Rabbe00** [rwdkor/RoKo#1]
I launched game before starting the bot and it is still saying scanning offset
![issue](https://user-images.githubusercontent.com/52624745/60767460-3f248100-a0c1-11e9-83d6-525feccb4b01.png)

**Comment by HassanSassan** [comment]
Bruhh...I think you should Start Osu! first then Run RoKo as Administrator :3
It worked for atleast

**Comment by HassanSassan** [comment]
> I launched game before starting the bot and it is still saying scanning offset
> ![issue](https://user-images.githubusercontent.com/52624745/60767460-3f248100-a0c1-11e9-83d6-525feccb4b01.png)

Bruhh...I think you should Start Osu! first then Run RoKo as Administrator :3
It worked for me atleast
