### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by nomad2018** [rwdkor/RoKo#5]
I've finally saw you updated the status of this and I was wondering if you're thinking about supporting other than 4k mode?

Just like 7k and even 5k, 6k, and 10k that are the most played ones.

Also, idk, make this a private hack then.
Pretty good work overall, really excited to see how it ends!

**Comment by rwdkor** [comment]
I already developed new program that supports all kinds of key, beatmaps(even non-mania map in mania mode).

I will release it ~ Oct, 10th

**Comment by rwdkor** [comment]
**https://github.com/rwdkor/RhythmSharp
RELEASED**
